require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - .git/**/*

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Exclude:
    - fillable-pdf.gemspec
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MutableConstant:
  Enabled: false
